// Generated by CoffeeScript 1.11.1

/*
Standard Array methods.
 */

(function() {
  BDS.Arrays = {};

  BDS.Arrays.swap = function(array, i1, i2) {
    var temp;
    temp = array[i1];
    array[i1] = array[i2];
    array[i2] = temp;
  };

  BDS.Arrays.binarySearch = function(array, elem_target, comparator) {
    var elem_current, max, mid, min;
    if (comparator === void 0) {
      comparator = function(a, b) {
        return a <= b;
      };
    }
    min = 0;
    max = array.length - 1;
    mid = Math.floor(max / 2);
    while (min <= max) {
      elem_current = array[mid];
      if (comparator(elem_current, elem_target)) {
        min = mid + 1;
      } else {
        max = mid - 1;
      }
      mid = Math.floor((min + max) / 2);
    }
    return min - 1;
  };

  BDS.Arrays.sortByValue = function(array) {
    var compare_func;
    compare_func = function(a, b) {
      return a.value - b.value;
    };
    return array.sort(compare_func);
  };

}).call(this);
