// Generated by CoffeeScript 1.11.1

/*
Standard Array methods.
 */

(function() {
  BDS.Arrays = {};

  BDS.Arrays.swap = function(array, i1, i2) {
    var temp;
    temp = array[i1];
    array[i1] = array[i2];
    array[i2] = temp;
  };

  BDS.Arrays.binarySearch = function(array, elem_target, comparator) {
    var elem_current, max, mid, min, results;
    min = 0;
    max = array.length;
    mid = max / 2;
    results = [];
    while (min < max) {
      results.push(elem_current = array[mid]);
    }
    return results;
  };

}).call(this);
