// Generated by CoffeeScript 1.11.1

/*
BDS.Math.Coffee
Written by Bryce Summers on 2 - 27 - 2017.
Purpose: Provides useful functions, such as Lerping.
 */

(function() {
  BDS.Math = {};

  BDS.Math.lerp = function(from, to, percentage) {
    return from * (1 - percentage) + to * percentage;
  };

}).call(this);

//# sourceMappingURL=math.js.map
