// Generated by CoffeeScript 1.11.1
(function() {
  BDS.Mesh = (function() {
    function Mesh(params) {
      var faces, triangles, vertices;
      this._vertices = null;
      this._face_indices = null;
      this._triangles = null;
      this._bvh = null;
      this._faceLink = null;
      if (params.soup) {
        this._vertices = params.vertices;
        this._face_indices = params.face_indices;
      }
      if (params.bvh) {
        triangles = params.triangles;
        if (!triangles) {
          triangles = this._triangles;
        }
        if (!triangles) {
          vertices = params.vertices;
          faces = params.face_indices;
          triangles = BDS.Mesh.construct_triangles(params.vertices, params.face_indices);
        }
        this._bvh = new BDS.BVH(triangles);
      }
    }

    Mesh.construct_triangles = function(vertices, face_indices) {};

    return Mesh;

  })();

}).call(this);
