// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BDS.Mesh = (function(superClass) {
    extend(Mesh, superClass);

    function Mesh(params) {
      var triangles;
      this._vertices = null;
      this._face_indices = null;
      this._triangles = null;
      this._bvh = null;
      this._faceLink = null;
      if (params.soup) {
        this._vertices = params.vertices;
        this._face_indices = params.face_indices;
      }
      if (params.bvh) {
        triangles = this._getInputTriangles(params);
        this._bvh = new BDS.BVH(triangles);
      }
      if (params.halfedge) {
        triangles = this._getInputTriangles(params);
        this._halfedgeMesh = new BDS.HalfedgeMesh(triangles);
      }
      if (params.faceLink) {
        this._faceLink = new BDS.FaceLinkGraph(params.face_indices);
      }
    }

    Mesh.prototype._getInputTriangles = function(params) {
      var faces, triangles, vertices;
      triangles = params.triangles;
      if (!triangles) {
        triangles = this._triangles;
      }
      if (!triangles) {
        vertices = params.vertices;
        faces = params.face_indices;
        triangles = BDS.Mesh.construct_triangles(params.vertices, params.face_indices);
      }
      params.triangles = triangles;
      return triangles;
    };

    Mesh.construct_triangles = function(vertices, face_indices) {
      var i, i1, i2, i3, j, output, ref, triangle, v1, v2, v3;
      output = [];
      for (i = j = 0, ref = face_indices.length; j < ref; i = j += 3) {
        i1 = face_indices[i];
        i2 = face_indices[i + 1];
        i3 = face_indices[i + 2];
        v1 = vertices[i1];
        v2 = vertices[i2];
        v3 = vertices[i3];
        triangle = new BDS.Triangle(v1, v2, v3);
        triangle.setIndices(i1, i2, i3);
        output.push(triangle);
      }
      return output;
    };

    Mesh.prototype.rayQueryMin = function(rayQuery) {
      this.ensure_bvh();
      return this._bvh.rayQueryMin(rayQuery);
    };

    Mesh.prototype.rayQueryAll = function(rayQuery) {
      this.ensure_bvh();
      return this._bvh.rayQueryAll(rayQuery);
    };

    Mesh.prototype.rayQueryTime = function(rayQuery) {
      var local_query;
      this.ensure_bvh();
      local_query = rayQuery.initialize(rayQuery.ray);
      if (this._bvh.rayQueryMin(local_query)) {
        rayQuery.time = local_query.min_time;
        return true;
      }
      return false;
    };

    Mesh.prototype.rayQueryTimes = function(rayQuery) {
      var j, len, local_query, ref, time;
      this.ensure_bvh();
      local_query = rayQuery.initialize(rayQuery.ray);
      if (this._bvh.rayQueryAll(local_query)) {
        ref = local.query_times;
        for (j = 0, len = ref.length; j < len; j++) {
          time = ref[j];
          rayQuery.times.push(time);
        }
        return true;
      }
      return false;
    };

    return Mesh;

  })(BDS.RayQueryable);

}).call(this);
