// Generated by CoffeeScript 1.11.1

/*

Triangle Set Constructors
Written by Bryce Summers on Aug.22.2017
 */

(function() {
  BDS.Mesh_Builder = (function() {
    function Mesh_Builder() {}

    Mesh_Builder.new_cube = function(transform) {
      var indices, pt000, pt001, pt010, pt011, pt100, pt101, pt110, pt111, pts;
      pt000 = new BDS.Point(0, 0, 0);
      pt001 = new BDS.Point(0, 0, 1);
      pt010 = new BDS.Point(0, 1, 0);
      pt011 = new BDS.Point(0, 1, 1);
      pt100 = new BDS.Point(1, 0, 0);
      pt101 = new BDS.Point(1, 0, 1);
      pt110 = new BDS.Point(1, 1, 0);
      pt111 = new BDS.Point(1, 1, 1);
      pts = [pt000, pt001, pt010, pt011, pt100, pt101, pt110, pt111];

      /*
      051
      045
      012
      132
      236
      376
      467
      475
      024
      264
      153
      357
       */
      indices = [0, 5, 1, 0, 4, 5, 0, 1, 2, 1, 3, 2, 2, 3, 6, 3, 7, 6, 4, 6, 7, 4, 7, 5, 0, 2, 4, 2, 6, 4, 1, 5, 3, 3, 5, 7];
      return BDS.Mesh.construct_triangles(pts, indices);
    };

    return Mesh_Builder;

  })();

}).call(this);
