// Generated by CoffeeScript 1.11.1

/*

Universal Input Controller.

Purpose: Interface for all user input controllers.
 */

(function() {
  BDS.Interface_Controller_All = (function() {
    function Interface_Controller_All() {
      this._active = true;
    }

    Interface_Controller_All.prototype.setActive = function(isActive) {
      return this._active = isActive;
    };

    Interface_Controller_All.prototype.isActive = function() {
      return this._active;
    };

    Interface_Controller_All.prototype.mouse_down = function(event) {};

    Interface_Controller_All.prototype.mouse_up = function(event) {};

    Interface_Controller_All.prototype.mouse_move = function(event) {};

    Interface_Controller_All.prototype.key_down = function(event) {};

    Interface_Controller_All.prototype.key_up = function(event) {};

    Interface_Controller_All.prototype.time = function(dt) {};

    Interface_Controller_All.prototype.window_resize = function(event) {};

    return Interface_Controller_All;

  })();

}).call(this);

//# sourceMappingURL=Interface_Controller_All.js.map
