// Generated by CoffeeScript 1.11.1

/*

Universal Input Controller.

Purpose: Interface for all user input controllers.
 */

(function() {
  BDS.Interface_Controller_Time = (function() {
    function Interface_Controller_Time() {
      this._active = true;
    }

    Interface_Controller_Time.prototype.setActive = function(isActive) {
      return this._active = isActive;
    };

    Interface_Controller_Time.prototype.isActive = function() {
      return this._active;
    };

    Interface_Controller_Time.prototype.time = function(dt) {};

    return Interface_Controller_Time;

  })();

}).call(this);
