// Generated by CoffeeScript 1.11.1

/*

Graphics Interface,

Written by Bryce Summers on 4 - 4 - 2017.


Purpose:

 - used to guide implementations of Graphics objects that may be used with BDS objects.
 */

(function() {
  BDS.Interface_G = (function() {
    function Interface_G() {}

    return Interface_G;

  })();

}).call(this);

//# sourceMappingURL=Interface_G.js.map
