// Generated by CoffeeScript 1.11.1

/*

Universal Input Controller.

Purpose: Interface for all user input controllers.
 */

(function() {
  BDS.Interface_Controller_All = (function() {
    function Interface_Controller_All() {
      this._active = false;
    }

    Interface_Controller_All.prototype.setActive = function(isActive) {};

    Interface_Controller_All.prototype.isActive = function() {};

    Interface_Controller_All.prototype.mouse_down = function(event) {};

    Interface_Controller_All.prototype.mouse_up = function(event) {};

    Interface_Controller_All.prototype.mouse_move = function(event) {};

    Interface_Controller_All.prototype.time = function(dt) {};

    Interface_Controller_All.prototype.window_resize = function(event) {};

    return Interface_Controller_All;

  })();

}).call(this);
