// Generated by CoffeeScript 1.11.1
(function() {
  BDS.aBezier_Curve = (function() {
    function aBezier_Curve(c0, c1, c2, c3) {}

    return aBezier_Curve;

  })();

}).call(this);

//# sourceMappingURL=bezier_curve.js.map
