// Generated by CoffeeScript 1.11.1

/*
Ray Class.

Written by Bryce Summers on 1 - 6 - 2017.

Purpose:
 */

(function() {
  BDS.Ray = (function() {
    function Ray(point, dir, _time_scale) {
      this.dir = dir;
      this._time_scale = _time_scale;
      if (this._time_scale === void 0) {
        this._time_scale = this.dir.norm();
        this.dir = this.dir.divScalar(this._time_scale);
      } else {
        this.dir = this.dir.normalize();
      }
      this.p1 = point;
      this.p2 = this.p1.add(this.dir);
    }

    Ray.prototype.getPoint = function() {
      return this.p1.clone();
    };

    Ray.prototype.getDirection = function() {
      return this.dir;
    };

    Ray.prototype.getTimeScale = function() {
      return this._time_scale;
    };

    Ray.prototype.detect_intersection_with_line = function(line) {
      var correct_direction, normal, side1, side2;
      side1 = this.line_side_test(line.p1);
      side2 = this.line_side_test(line.p2);
      normal = line.getNormal(this.p1);
      correct_direction = normal.dot(this.dir) < 0;
      return side1 * side2 <= 0 && correct_direction;
    };

    Ray.prototype.line_side_test = function(c) {
      return (this.p2.x - this.p1.x) * (c.y - this.p1.y) - (this.p2.y - this.p1.y) * (c.x - this.p1.x);
    };

    Ray.prototype.getAngle = function() {
      return Math.atan2(this.p2.y - this.p1.y, this.p2.x - this.p1.x);
    };

    return Ray;

  })();

}).call(this);
